export const LOGOUT = 'LOGOUT';

//manager waitingList DB
export const FETCH_WAITING_LIST_USERS = 'FETCH_WAITING_LIST_USERS'
export const ACCESS_DENIED = 'ACCESS_DENIED'

export const FETCH_PRODUCT_CONTENT = 'FETCH_PRODUCT_CONTENT'

export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST'
export const FETCH_LIVER_ORDER_PRODUCT = 'FETCH_LIVER_ORDER_PRODUCT'

export const FETCH_DIRECT_ORDER_LIST = 'FETCH_DIRECT_ORDER_LIST'

export const FETCH_PURCHASE_INFO = 'FETCH_PURCHASE_INFO'

export const FETCH_CART_COUNT = 'FETCH_CART_COUNT'
export const FETCH_MY_CART_INFO = 'FETCH_MY_CART_INFO'

export const FETCH_MULTI_PRODUCT_INFO = 'FETCH_MULTI_PRODUCT_INFO'