export const LOGOUT = 'LOGOUT';

//manager waitingList DB
export const FETCH_WAITING_LIST_USERS = 'FETCH_WAITING_LIST_USERS'
export const ACCESS_DENIED = 'ACCESS_DENIED'

export const FETCH_PRODUCT_CONTENT = 'FETCH_PRODUCT_CONTENT'

export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST'
export const FETCH_LIVER_ORDER_PRODUCT = 'FETCH_LIVER_ORDER_PRODUCT'