server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bossi_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: reuma
    password: reuma@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b9c2e3676f2b38d4b2f5575e61982b97
            client-secret: Sj9kkm66JAew72RI2Cjgqs7jV6uLPFGj
            redirect-uri: http://localhost:7777/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

          google:
            client-id: 869037245265-951o838u6qe2o7krrhaeunhac3ej8du7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          github:
            client-id: Iv1.310effb41d8ed795
            client-secret: d36a9d73444adfabb30678f6f2c0647df6bb526d

          naver:
            client-id: 2cspIEB2B0KLJ8s7MXJI
            client-secret: hHecX3FmNp
            redirect-uri: http://localhost:7777/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - nickname
              - profile_img
              - phone_number

            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response




