server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bossi_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: reuma
    password: reuma@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  profiles:
    include: API-KEY
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "${KAKAO-CLIENT-ID}"
            client-secret: "${KAKAO-CLIENT-SECRET}"
            redirect-uri: "${KAKAO-REDIRECT-URI}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

          google:
            client-id: "${GOOGLE-CLIENT-ID}"
            client-secret: "${GOOGLE-CLIENT-SECRET}"
            scope:
              - profile
              - email

          github:
            client-id: "${GITHUB-CLIENT-ID}"
            client-secret: "${GITHUB-CLIENT-SECRET}"

          naver:
            client-id: "${NAVER-CLIENT-ID}"
            client-secret: "${NAVER-CLIENT-SECRET}"
            redirect-uri: "${NAVER-REDIRECT-URI}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - nickname
              - profile_img
              - phone_number

            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response




